### ISSUE TITLE
VerifyError while running Junit tests with Robolectric

### ISSUE THREAD

**Issue by renatacmn** [freshdesk/freshchat-android#15]
While trying to run the test suite using Robolectric, the FreshChat SDK gives a 'VerifyError'.

The stack trace is the following:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 24
Exception Details:
  Location:
    com/freshchat/consumer/sdk/receiver/FreshchatReceiver.a(Landroid/content/Intent;Ljava/lang/String;)Z @1: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2bc6 0017 2cb8 0023 9900 102c 2bb6 001c
    0x0000010: b600 3499 0005 04ac 03ac               


	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:340)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:35)
	at org.robolectric.android.internal.ParallelUniverse.registerBroadcastReceivers(ParallelUniverse.java:388)
	at org.robolectric.android.internal.ParallelUniverse.createApplication(ParallelUniverse.java:258)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:168)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

```

**Comment by tryprasannan** [comment]
@renatacmn Thanks for reporting this. We are looking into it.

**Comment by MuthuFD** [comment]
@renatacmn @bernardo-macedo 

Hi, We are released a canary for this. Can you verify and let us know.

**Comment by MuthuFD** [comment]
@bernardo-macedo Use this dependency 
compile 'com.github.freshdesk:freshchat-android:canary-SNAPSHOT'.

**Comment by renatacmn** [comment]
@MuthuFD @tryprasannan it worked for me, thanks!

**Comment by tryprasannan** [comment]
@renatacmn @bernardo-macedo We found some issues related to this and have released a version with fix for it. Recommend updating to [version 1.4.0](https://github.com/freshdesk/freshchat-android/releases/tag/1.4.0)

**Comment by renatacmn** [comment]
Thank you. Did this and it worked!
