### ISSUE TITLE
Connection refused when sending firebase token.

### ISSUE THREAD

**Issue by RHMDHDYT** [freshdesk/freshchat-android#2]
I've got this message when sending firebase token : 

```
E/FRESHCHAT: Exception on asus ASUS_Z017DB Android API 7.0 (24)
             java.lang.RuntimeException: java.net.ConnectException: Connection refused
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source)
                 at com.freshchat.consumer.sdk.e.c.ae(Unknown Source)
                 at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source)
                 at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source)
                 at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source)
                 at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source)
                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:159)
                 at android.os.HandlerThread.run(HandlerThread.java:61)
              Caused by: java.net.ConnectException: Connection refused
                 at java.net.PlainSocketImpl.socketConnect(Native Method)
                 at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                 at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                 at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                 at java.net.Socket.connect(Socket.java:586)
                 at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                 at com.android.okhttp.Connection.connectSocket(Connection.java:196)
                 at com.android.okhttp.Connection.connect(Connection.java:172)
                 at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                 at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source)
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source) 
                 at com.freshchat.consumer.sdk.e.c.ae(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source) 
                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                 at android.os.Looper.loop(Looper.java:159) 
                 at android.os.HandlerThread.run(HandlerThread.java:61) 
```

this is my code inside firebase instance id service.

```
@Override
  public void onTokenRefresh() {
    // Get updated InstanceID token.
    String refreshedToken = FirebaseInstanceId.getInstance().getToken();
 
    if (refreshedToken != null) {
      Freshchat.getInstance(this).setPushRegistrationToken(refreshedToken);
    }
  }
```

**Comment by RHMDHDYT** [comment]
I think it is because I initializing Freshchat in application class, not in activity class. problem solved after i move init code on activity class.
