### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError Failed

### ISSUE THREAD

**Issue by ratdream** [freshdesk/freshchat-android#22]
Hi all

When app update freshchat to  1.4.0 version, I find some NoClassDefFoundError on fabric.

The following is exception message:

Caused by java.lang.ClassNotFoundException: Didn't find class "android.support.v4.graphics.drawable.DrawableWrapper" on path: DexPathList[[zip file ""],nativeLibraryDirectories=[]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:149)
       at android.support.v7.widget.AppCompatDrawableManager.tintDrawableUsingColorFilter(AppCompatDrawableManager.java:468)
       at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:294)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
       at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
       at android.support.v7.app.AppCompatDelegateImplBase.(AppCompatDelegateImplBase.java:128)
       at android.support.v7.app.AppCompatDelegateImplV9.(AppCompatDelegateImplV9.java:149)
       at android.support.v7.app.AppCompatDelegateImplV11.(AppCompatDelegateImplV11.java:29)
       at android.support.v7.app.AppCompatDelegateImplV14.(AppCompatDelegateImplV14.java:54)
       at android.support.v7.app.AppCompatDelegateImplV23.(AppCompatDelegateImplV23.java:31)
       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:200)
       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:192)
       at android.support.v7.app.AppCompatDialog.getDelegate(AppCompatDialog.java:158)
       at android.support.v7.app.AppCompatDialog.(AppCompatDialog.java:52)
       at android.support.v7.app.AlertDialog.(AlertDialog.java:97)
       at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:932)
       at com.freshchat.consumer.sdk.activity.ConversationDetailActivity.b(Unknown Source)
       at com.freshchat.consumer.sdk.activity.ConversationDetailActivity.c(Unknown Source)
       at com.freshchat.consumer.sdk.activity.ConversationDetailActivity$6.onClick(Unknown Source)
       at android.view.View.performClick(View.java:5714)
       at android.widget.TextView.performClick(TextView.java:10926)
       at android.view.View$PerformClick.run(View.java:22589)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Hope for response, Thanks

**Comment by tryprasannan** [comment]
@ratdream 
1) Can you share more information about your dependencies(esp the support lib versions)? 
2) Has the dependencies or dependencies' version changed recently ?
3) Is it reproducible for you locally or do you see this happening on one of your devices?  

Freshchat SDK's target versions or dependencies haven't changed in the last couple of releases

**Comment by MuthuFD** [comment]
Closing this issue. If you are still facing this issue in our latest version, feel free to reopen
