### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by chaitanya-exp** [freshdesk/freshchat-android#23]
The following crash happens in version 1.2.1.
I am not able to reproduce this. Found these crashes on fabric.

Fatal Exception: java.lang.IncompatibleClassChangeError: com.freshchat.consumer.sdk.d.a
       at dalvik.system.DexFile.defineClassNative(DexFile.java)
       at dalvik.system.DexFile.defineClass(DexFile.java:226)
       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
       at dalvik.system.DexPathList.findClass(DexPathList.java:338)
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.freshchat.consumer.sdk.j.ab.(Unknown Source)
       at com.freshchat.consumer.sdk.j.ab.(Unknown Source)
       at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.c.g.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tryprasannan** [comment]
@chaitanya-exp Thanks for reporting this. Do you have any more information on device and os information? Can you also share your app's info (target/compile etc, dependency list & versions etc)

**Comment by chaitanya-exp** [comment]
<img width="1009" alt="screen shot 2018-07-27 at 4 40 59 pm" src="https://user-images.githubusercontent.com/6319140/43317811-ef844ed8-91bb-11e8-87c2-9a289d00e897.png">
@tryprasannan

**Comment by chaitanya-exp** [comment]
@tryprasannan  compileSdk : 26

**Comment by skybur** [comment]
Any news on this? I also get this error after upgrading to AndroidX
```
E/AndroidRuntime(12916): java.lang.IncompatibleClassChangeError: Class 'com.freshchat.consumer.sdk.activity.ChannelListActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/id.kulina.app.dev-2/base.apk:classes2.dex)
E/AndroidRuntime(12916): 	at androidx.lifecycle.LiveData.observe(LiveData.java:172)
E/AndroidRuntime(12916): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
E/AndroidRuntime(12916): 	at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
E/AndroidRuntime(12916): 	at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
E/AndroidRuntime(12916): 	at com.freshchat.consumer.sdk.activity.ChannelListActivity.F(Unknown Source)
E/AndroidRuntime(12916): 	at com.freshchat.consumer.sdk.activity.ChannelListActivity.onResume(Unknown Source)
E/AndroidRuntime(12916): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
E/AndroidRuntime(12916): 	at android.app.Activity.performResume(Activity.java:6431)
E/AndroidRuntime(12916): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3177)
E/AndroidRuntime(12916): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3219)
E/AndroidRuntime(12916): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2550)
E/AndroidRuntime(12916): 	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
E/AndroidRuntime(12916): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
E/AndroidRuntime(12916): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12916): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(12916): 	at android.app.ActivityThread.main(ActivityThread.java:5601)
E/AndroidRuntime(12916): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12916): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
E/AndroidRuntime(12916): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
I/Process (12916): Sending signal. PID: 12916 SIG: 9
```

**Comment by JordyRiwal** [comment]
We are also getting this error.

Fresh chat version 2.6.0
CompileSdkVersion 28
MinSdkVersion 21
TargetSdkVersion 28

This is how we use it:
```
chatButton.setOnClickListener {
   Freshchat.showConversations(context, CONSERVATION_OPTIONS)
}
```
This is the error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IncompatibleClassChangeError: Class 'com.freshchat.consumer.sdk.activity.InterstitialActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.riwal.rentalapp.development-jH3fOaDQ6nLqwHHJEJhqhg==/base.apk!classes3.dex)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
        at com.freshchat.consumer.sdk.activity.InterstitialActivity.aE(Unknown Source:54)
        at com.freshchat.consumer.sdk.activity.InterstitialActivity.onCreate(Unknown Source:77)
        at android.app.Activity.performCreate(Activity.java:7163)
        at android.app.Activity.performCreate(Activity.java:7154)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3087)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7009)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MuthuFD** [comment]
Hi @chaitanya-exp, Are you still facing this issue in our latest version. 

Please update to our latest SDK version.

Closing this issue. If you are still facing this issue in our latest version, feel free to reopen

**Comment by JordyRiwal** [comment]
Hi @MuthuFD,
Why is this issue closed? 6 days ago I added a comment that this issue still occurs in your latest SDK and that we are now not able to use FreshChat in the app! Please fix this ASAP.

**Comment by MuthuFD** [comment]
Hi @JordyRiwal, Thanks for letting us know. 
We need few more details. Can you contact us through support@freshchat.com

Reopening this issue.

**Comment by JordyRiwal** [comment]
Updating the constraint layout to a stable version, fixed the issue for me:
`implementation 'androidx.constraintlayout:constraintlayout:1.1.3'`

**Comment by sagarbandamwar** [comment]
i am getting same issue since one week and i have no idea how to get rid of this
@JordyRiwal  i have used stable version of every dependency i added to my gradle

java.lang.IncompatibleClassChangeError: Class 'com.freshchat.consumer.sdk.activity.ChannelListActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.devere.savingsapp-HXsrdgvjg5uBbPC_KqnV1g==/base.apk:classes3.dex)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.F(Unknown Source:46)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.onResume(Unknown Source:80)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7353)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

would you mind looking at this error

**Comment by JordyRiwal** [comment]
@sagarbandamwar Can you share your gradle dependencies?

**Comment by sagarbandamwar** [comment]
@JordyRiwal  // here it is
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation("androidx.test.espresso:espresso-core:3.1.0"){
        exclude module: 'support-annotations'
        exclude module: 'support-v4'
        exclude module: 'support-v13'
        exclude module: 'recyclerview-v7'
    }

    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$rootProject.kotlin_version"

    // android support libraries
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
//    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.0.0-beta01'
    implementation 'androidx.vectordrawable:vectordrawable:1.0.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.0.0'

    implementation "androidx.lifecycle:lifecycle-extensions:2.0.0"
    implementation "androidx.lifecycle:lifecycle-runtime:2.0.0"
    kapt "androidx.lifecycle:lifecycle-compiler:2.0.0"
    implementation "androidx.lifecycle:lifecycle-livedata:2.0.0"



    // network
    implementation "com.amitshekhar.android:rx2-android-networking:$rootProject.rx2FastAndroidNetworking"
    //implementation "com.amitshekhar.android:jackson-android-networking:$rootProject.rx2FastAndroidNetworking"

    // database
    implementation 'androidx.room:room-rxjava2:2.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    kapt 'androidx.room:room-compiler:2.0.0'

    // UI Testing
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.2.0'

    //multi dex
    implementation 'androidx.multidex:multidex:2.0.1'

    // Android Kotlin Extension
    implementation "androidx.core:core-ktx:$rootProject.androidKTXVersion"

    //Camera X dependencies

    implementation "androidx.camera:camera-core:$rootProject.camerax_version"
    implementation "androidx.camera:camera-camera2:$rootProject.camerax_version"

    // font
    implementation "uk.co.chrisjenx:calligraphy:$rootProject.calligraphyVersion"

    // image
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'

    // parser
    implementation "com.google.code.gson:gson:$rootProject.gsonVersion"

    // debug database
    debugImplementation "com.amitshekhar.android:debug-db:$rootProject.debugDBVersion"

    // dependency injection
    implementation "com.google.dagger:dagger:$rootProject.dagger2Version"
    kapt "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    kapt "com.google.dagger:dagger-android-processor:$rootProject.dagger2Version"
    implementation "com.google.dagger:dagger-android-support:$rootProject.dagger2Version"

    // reactive
    implementation "io.reactivex.rxjava2:rxjava:$rootProject.rxjava2Version"
    implementation "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"

    // code generator for view
    implementation "com.jakewharton:butterknife:$rootProject.butterKnifeVersion"
    kapt "com.jakewharton:butterknife-compiler:$rootProject.butterKnifeVersion"

    // swipe view
    implementation "com.mindorks:placeholderview:$rootProject.placeholderviewVersion"

    // logger
    implementation "com.jakewharton.timber:timber:$rootProject.timberVersion"

    // dependencies for local unit tests
    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    testImplementation "org.mockito:mockito-core:$rootProject.mockitoVersion"
    kaptTest "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    androidTestImplementation "org.mockito:mockito-core:$rootProject.mockitoVersion"
    kaptAndroidTest "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    //dpi
    implementation 'com.intuit.sdp:sdp-android:1.0.5'

    //firebase sdk
    implementation 'com.google.firebase:firebase-core:16.0.9'

    implementation 'com.google.firebase:firebase-core:16.0.9'

    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.0'
    implementation 'com.google.firebase:firebase-appindexing:18.0.0'

    //cloud messaging
    implementation 'com.google.firebase:firebase-messaging:18.0.0'

    //freshchat
    implementation "com.github.freshdesk:freshchat-android:$rootProject.freshChatVersion"

    //jackson
    implementation 'com.fasterxml.jackson.core:jackson-core:2.9.7'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.7'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.7'

    // circleimage view
    implementation "de.hdodenhof:circleimageview:$rootProject.circleImageView"

    //Validation
    implementation 'com.mobsandgeeks:android-saripaar:2.0.3'

    //sp size unit (for texts).
    implementation 'com.intuit.ssp:ssp-android:1.0.6'

    //
    implementation 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:2.0.0'


    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    //
    implementation "com.github.ArmanSar:SwipeLayout:1.0.10"

}

ext {
    // Sdk and tools
    minSdkVersion = 21
    targetSdkVersion = 28
    compileSdkVersion = 28
    buildToolsVersion = '26.0.2'

    // App dependencies
    supportLibraryVersion = '28.0.0'
    gsonVersion = '2.8.0'
    calligraphyVersion = '2.2.0'
    glideVersion = '4.9.0'
    rx2FastAndroidNetworking = '1.0.2'
    dagger2Version = '2.16'
    rxjava2Version = '2.2.2'
    rxandroidVersion = '2.1.0'
    butterKnifeVersion = '10.1.0'
    roomDatabaseVersion = '1.0.0'
    placeholderviewVersion = '0.6.1'
    debugDBVersion = '1.0.3'
    timberVersion = '4.6.0'
    freshChatVersion = '2.6.1'
    circleImageView = '3.0.0'
    camerax_version = '1.0.0'
//    camerax_version = '1.0.0-alpha03'


    //Test dependencies
    junitVersion = '4.12'
    espressoVersion = '2.2.2'
    mockitoVersion = '2.7.1'
    androidKTXVersion = '1.0.2'


}

**Comment by sagarbandamwar** [comment]
> @sagarbandamwar Can you share your gradle dependencies?

please take a look

**Comment by sagarbandamwar** [comment]
> @sagarbandamwar Can you share your gradle dependencies?

@JordyRiwal  I have shared the Gradles please take a look and help me out

**Comment by JordyRiwal** [comment]
Hi @sagarbandamwar, I checked your dependencies but they look oke to me. I think you can better contact Freshchat support@freshchat.com for this issue
