### ISSUE TITLE
Crash when app is in background

### ISSUE THREAD

**Issue by pritamps** [freshdesk/freshchat-android#25]
Hello,

I'm getting the following crash in our app when using Freshchat. It seems to happen when the app is in Background on Android 8 devices. The stacktrace:

```
07-25 15:52:02.850 1450-1450/in.avanti.gurukul.learning.cbse.ncert.iit.video.test.doubt E/FRESHCHAT: Exception on Xiaomi Mi A1 Android API 8.1.0 (27) >>>>> Not allowed to start service Intent { cmp=in.avanti.gurukul.learning.cbse.ncert.iit.video.test.doubt/com.freshchat.consumer.sdk.service.FreshchatService }: app is in background uid UidRecord{be759a0 u0a162 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
   java.lang.IllegalStateException: Not allowed to start service Intent { cmp=in.avanti.gurukul.learning.cbse.ncert.iit.video.test.doubt/com.freshchat.consumer.sdk.service.FreshchatService }: app is in background uid UidRecord{be759a0 u0a162 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
       at android.app.ContextImpl.startService(ContextImpl.java:1477)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at com.freshchat.consumer.sdk.service.FreshchatService.r(Unknown Source:7)
       at com.freshchat.consumer.sdk.service.FreshchatService.a(Unknown Source:10)
       at com.freshchat.consumer.sdk.service.d.d.c(Unknown Source:4)
       at com.freshchat.consumer.sdk.j.b.a(Unknown Source:24)
       at com.freshchat.consumer.sdk.Freshchat.getUnreadCountAsync(Unknown Source:30)
       at in.avanti.studentcompanion.StudentCompanion.getFreshChatUnreadCount(StudentCompanion.java:108)
       at in.avanti.studentcompanion.StudentCompanion.onCreate(StudentCompanion.java:89)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5776)
       at android.app.ActivityThread.-wrap1(Unknown Source:0)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6590)
       at java.lang.reflect.Method.invoke(Native Method)  in my device
```

The exact line that seems to be causing this crash is:    **`at com.freshchat.consumer.sdk.Freshchat.getUnreadCountAsync(Unknown Source:30)
       at`**

The issue seems to be something related to what is described in [this Stackoverflow issue](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten), where the `startService` method needs to be used more carefully (or replaced with other methods) starting with Android 8.0 . 

Is the Freshchat team looking at this? Can I do something in my app to avoid this crash?

**Comment by tryprasannan** [comment]
@pritamps Thanks for reporting this. This is not a crash, we log it when this happens. That said we'll work on improving this experience.

**Comment by paulsUsername** [comment]
Hmmm seems to be causing a crash for me
