### ISSUE TITLE
Infinite Loading in Chat when set domain FreshChatConfig in Android 4.4.2 devices Fresh Chat sdk version {1.5.0}

### ISSUE THREAD

**Issue by kabirkhaan** [freshdesk/freshchat-android#27]
Fresh is showing infinity indicator when domain are set to `FreshChatConfig` below Android 5.0 devices.

```
E/FRESHCHAT: Exception on samsung SM-G386F Android API 4.2.2 (17) >>>>> javax.net.ssl.SSLException: Connection closed by peer
             java.lang.RuntimeException: javax.net.ssl.SSLException: Connection closed by peer
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source)
                 at com.freshchat.consumer.sdk.service.d.a.v(Unknown Source)
                 at com.freshchat.consumer.sdk.service.c.d.a(Unknown Source)
                 at com.freshchat.consumer.sdk.service.c.d.b(Unknown Source)
                 at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source)
                 at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source)
                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                 at android.os.Handler.dispatchMessage(Handler.java:99)
                 at android.os.Looper.loop(Looper.java:176)
                 at android.os.HandlerThread.run(HandlerThread.java:60)
              Caused by: javax.net.ssl.SSLException: Connection closed by peer
                 at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
                 at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:379)
                 at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:231)
                 at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
                 at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
                 at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
                 at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
                 at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
                 at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
                 at com.google.firebase.perf.network.zze.connect(Unknown Source)
                 at com.google.firebase.perf.network.zzd.connect(Unknown Source)
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source)
                 at com.freshchat.consumer.sdk.e.c.a(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.d.a.v(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.c.d.a(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.c.d.b(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source) 
                 at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source) 
                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                 at android.os.Looper.loop(Looper.java:176) 
                 at android.os.HandlerThread.run(HandlerThread.java:60) 
```

**Comment by tryprasannan** [comment]
@kabirkhaan Can you uninstall/install app and confirm if it still happens ? Can you also share what domain you're specifying ?

**Comment by kabirkhaan** [comment]
@tryprasannan thanks for your reply, I tried already and it not working. However If don't set the domain in `Android 4.4` it works fine. But When I tried to set the domain `msdk.eu.freshchat.com` it shows an exception on `LOGCAT` which I have posted in my ticket. 

Moreover `domain` are working fine in all other Android versions.

**Comment by tryprasannan** [comment]
@kabirkhaan Are you using the same app id and app key combination whens specifying the domain vs when not specifying the domain ?

**Comment by kabirkhaan** [comment]
@tryprasannan We have different apps having different set of configurations. Issue arises when `Fresh chat config` have domain. One which does not have `domain` load fine.

**Comment by tryprasannan** [comment]
@kabirkhaan Can you share the app id/alias of the specific accounts that you are integrating over email to `support@freshchat.com` for us to get this checked ?

**Comment by kabirkhaan** [comment]
@tryprasannan Thanks alot for fixing this use. We have tested on our side :) 🎉 🎉 🎉 🎉 🎉

**Comment by Shekhar7860** [comment]
hi @tryprasannan can you help me with freshChat conversations issue???
