### ISSUE TITLE
Crash on uploading a image

### ISSUE THREAD

**Issue by srinivas3120** [freshdesk/freshchat-android#30]
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in base.apk:classes3.dex)
        at com.freshchat.consumer.sdk.j.t.<init>(Unknown Source)
        at com.freshchat.consumer.sdk.j.t.<init>(Unknown Source)
        at com.freshchat.consumer.sdk.j.t$a.eA(Unknown Source)
        at com.freshchat.consumer.sdk.j.t.aw(Unknown Source)
        at com.freshchat.consumer.sdk.j.ak.a(Unknown Source)
        at com.freshchat.consumer.sdk.j.ak.a(Unknown Source)
        at com.freshchat.consumer.sdk.a.d.getView(Unknown Source)
        at android.widget.AbsListView.obtainView(AbsListView.java:2474)
        at android.widget.ListView.makeAndAddView(ListView.java:1920)
        at android.widget.ListView.fillUp(ListView.java:751)
        at android.widget.ListView.layoutChildren(ListView.java:1696)
        at android.widget.AbsListView.onLayout(AbsListView.java:2235)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
        at android.view.View.layout(View.java:16969)
        at android.view.ViewGroup.layout(ViewGroup.java:5583)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2552)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2255)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
        at android.os.Handler.handleCallback(Handler.java:822)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by srinivas3120** [comment]
freshchat is using older version of picasso 'com.squareup.picasso:picasso:2.5.2' 
we are using the newer version of picasso 'com.squareup.picasso:picasso:2.71828' where some methods are removed.
I can't downgrade library version. 

Please provide a solution or upgrade to latest version of picasso.

**Comment by MuthuFD** [comment]
Hi @srinivas3120 , 
Freshchat SDK uses Picasso 2.5.2. Picasso's latest version has breaking changes so if you use the latest version, you will be face this issue.
We actively looking to make this experience better.

We will keep this thread updated on our progress regarding the fix.

**Comment by elitelokesh** [comment]
Hi,
I'm also getting the same error, hope this will be resolved soon.
**Error 1**
java.io.**FileNotFoundException**: https:/fc-use1-00-pics-bkt-00.s3.amazonaws.com/fa339fe68d6765947cf57a138f6a02265bd4e7a26fd82640f9d3a8d7c4d4fa87/f_marketingpicFull/u_715ef9e79d9c83da6875a17741510141c533f443669a0c39f9fea5807ff9b726/img_1537197590701.jpeg (No such file or directory)

**Error 2**
java.lang.**NoSuchMethodError**: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/in.hipbar.hipbar_user_app.dev-Z1VnfUgbK-pIt997Z_kXsA==/base.apk!classes3.dex)

Please update the fix with the latest version of Picasso 'com.squareup.picasso:picasso:2.71828'

**Comment by MuthuFD** [comment]
@srinivas3120 @elitelokesh 
From Freshchat SDK version 1.5.2, we allow setting custom image loaders.

SDK defaults to including Picasso 2.5.2 library to download images. If you want to use any other version of Picasso or any other Image download library, you can set your custom image downloader with Freshchat SDK using setImageLoader() API.

Eg:
Implement your custom image loader
```
public class CustomImageLoader implements FreshchatImageLoader {
  
  @Override
  public void load(@NonNull FreshchatImageLoaderRequest request, @NonNull ImageView imageView) {
    // your code to download image and set to imageView
  }

  @Nullable
  @Override
  public Bitmap get(@NonNull FreshchatImageLoaderRequest request) {
    // code to download and return bitmap image
  }

  @Override
  public void fetch(@NonNull FreshchatImageLoaderRequest request) {
    // code to download image
  }
}
```

Call Freshchat.setImageLoader() in onCreate() of your Application class
```
public class MyApp extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    Freshchat.setImageLoader(new CustomImageLoader());
  }
}
```
