### ISSUE TITLE
App crashes at last time

### ISSUE THREAD

**Issue by vishnyakov-aleks** [freshdesk/freshchat-android#36]
FreshChat does not run, when call .showConversations()

```
   java.lang.RuntimeException: Not implemented. Must override in a subclass.
        at android.content.Context.bindServiceAsUser(Context.java:2612)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.F(Unknown Source)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.a(Unknown Source)
        at com.freshchat.consumer.sdk.activity.b$1.onReceive(Unknown Source)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6533)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

```

On AVD and meizu was tested

**Comment by vishnyakov-aleks** [comment]
Closed, crash was caused by my dependency in basequickadapter 
now i using this dependency without crashes
    api 'androidx.recyclerview:recyclerview:1.0.0'
instead of
    api 'androidx.recyclerview:recyclerview:1.1.0-alpha01'


Sorry =)
