### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Unknown pattern character 'Y'

### ISSUE THREAD

**Issue by StevenStarz** [freshdesk/freshchat-android#38]
Fatal Exception: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
       at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
       at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
       at com.freshchat.consumer.sdk.j.n.bp(Unknown Source)
       at com.freshchat.consumer.sdk.j.n.a(Unknown Source)
       at com.freshchat.consumer.sdk.a.c.getView(Unknown Source)
       at android.widget.AbsListView.obtainView(AbsListView.java:2346)
       at android.widget.ListView.makeAndAddView(ListView.java:1876)
       at android.widget.ListView.fillDown(ListView.java:702)
       at android.widget.ListView.fillFromTop(ListView.java:763)
       at android.widget.ListView.layoutChildren(ListView.java:1671)
       at android.widget.AbsListView.onLayout(AbsListView.java:2148)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
       at android.view.View.layout(View.java:16652)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2176)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1936)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6035)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by StevenStarz** [comment]
Hello, Can someone help me with this error.

**Comment by StevenStarz** [comment]
This error thrown when i calling this script
Freshchat.showConversations()

**Comment by tryprasannan** [comment]
@StevenStarz Can you confirm what version of SDK are you on ? If you are not on latest, we would recommend you update to 2.0.1 and check

**Comment by MuthuFD** [comment]
We are closing this issue. Please feel free to reopen if you are still facing this issue.
