### ISSUE TITLE
UncaughtException: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by sdj9391** [freshdesk/freshchat-android#50]
I am trying to open Freshchat conversation 
`Freshchat.showConversations(getApplicationContext());`

```
E/UncaughtException: java.lang.IncompatibleClassChangeError: Class 'com.freshchat.consumer.sdk.activity.ChannelListActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.healthpole.dentists.debug-X-W_P0gIA-gphdr95wNXzg==/base.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.F(Unknown Source:46)
        at com.freshchat.consumer.sdk.activity.ChannelListActivity.onResume(Unknown Source:80)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

`Project Configuration`
minimumSdkVersion -> 21
compileSdkVersion -> 28
FreshChat SDK version -> com.github.freshdesk:freshchat-android:2.6.0
and migrated to androidX

`NOTE`
I have tried using the updated version of [constraintlayout](https://github.com/freshdesk/freshchat-android/issues/23) 
also used [appcompat-v7-28.0.0 and support-v4-28.0.0](https://github.com/techaffinity/freshchat-phonegap/issues/25) lib still facing the same issue.

so my question is what more dependencies I have to changes or add?

**Comment by MuthuFD** [comment]
Hi @sdj9391 , Looks like this same [issue](https://github.com/freshdesk/freshchat-android/issues/23#issuecomment-477083478). 

Please use stable AndroidX libraries if you not.

**Comment by sdj9391** [comment]
Hi @MuthuFD, I have updated appcompact lib and thank you it is working fine.
