### ISSUE TITLE
Crash when initializing in Android 8 (Oreo)

### ISSUE THREAD

**Issue by gnumilanix** [freshdesk/freshchat-android#8]
We did following in our applications `onCreate()` method. It is fine with older versions of Android but, crashes on Android O if it was called when the app is in the background. This is probably due to **Background Service Limitations** as described in [here](https://developer.android.com/about/versions/oreo/background.html#services)
```java
Freshchat.getInstance(getApplicationContext()).init(getFreshchatConfig());
```

Here's a crash log:
```java
 Exception on Xiaomi Mi A1 Android API 8.0.0 (26)
   java.lang.IllegalStateException: Not allowed to start service Intent { cmp=hk.easyvan.app.driver2/com.freshchat.consumer.sdk.service.FreshchatService }: app is in background uid UidRecord{916d6b2 u0a145 TRNB idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.freshchat.consumer.sdk.service.FreshchatService.r(Unknown Source:7)
       at com.freshchat.consumer.sdk.service.FreshchatService.a(Unknown Source:10)
       at com.freshchat.consumer.sdk.service.d.d.b(Unknown Source:9)
       at com.freshchat.consumer.sdk.j.b.T(Unknown Source:8)
       at com.freshchat.consumer.sdk.Freshchat.init(Unknown Source:126)
       at com.lalamove.app.App.initLocalizedSDKs(App.java:140)
       at com.lalamove.app.App.onCreate(App.java:105)`

**Comment by tryprasannan** [comment]
@gnumilanix Thanks for reporting, this is also one of the reasons our integration guide recommends invoking init() from onCreate() of launcher/main activity and not  application

**Comment by gnumilanix** [comment]
@tryprasannan wondering if `Freshchat.handleGcmMessage(..)` will cause a crash if we only initialize in the `Activity.onCreate()`?

Since, after a system restart, the app needs to still be able to receive pushes. But, `Freshchat.init()` would never have been called. 

Any plans to implement `FreshchatService` with `JobScheduler` or similar APIs?

**Comment by tryprasannan** [comment]
@gnumilanix You can safely invoke handleGcmMessage () before init() as well. The SDK already has Alarm based auto retry, but not JobScheduker at the moment.

**Comment by tryprasannan** [comment]
@gnumilanix Sorry, missed your other query reg launching from Shortcut manager, you can use a trampoline activity, or an invisible activity that invokes Freshchat.init() and starts the Freshchat activity in onCreate(), then calls finish(). It wouldn't be recommended to call init from every screen.
